tunnel: dd3d6d80-0cbc-4008-a982-042a2adb9e93
credentials-file: ~/.cloudflared/dd3d6d80-0cbc-4008-a982-042a2adb9e93.json

ingress:
  - hostname: development.dancigrang.dev
    service: http://localhost:4321
  - service: http_status:404